[project]
name = "otoku-xml-parser"
version = "0.0.1-alpha.1"
description = "An xml parser for the JMDict, KanjiDIC and related files."
requires-python = ">=3.9"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["otoku_xml_parser*"]